=== Petee99/E8HZ8D_XMLGyak/E8HZ8D_0928/MP_konyv.dtd
<!ELEMENT konyvek (konyv+)>
<!ELEMENT konyv (cim,kiadasiEv,kiado,szerzok,absztrakt?)>
<!ELEMENT szerzok (szerzo+)>
<!ATTLIST konyv id ID #REQUIRED>
<!ELEMENT cim (#PCDATA)>
<!ELEMENT kiadasiEv (#PCDATA)>
<!ELEMENT kiado (#PCDATA)>
<!ELEMENT szerzo (#PCDATA)>
<!ELEMENT absztrakt (#PCDATA)>

=== Petee99/E8HZ8D_XMLGyak/E8HZ8D_0928/MP_konyv.xml
<?xml version="1.0"?>
<!DOCTYPE konyvek SYSTEM "./MP_konyv.dtd">
<konyvek>
    <konyv id="info_konyv_1">
        <cim>
            Gyors kontextusalapu tervezes
        </cim>
        <kiadasiEv>
            2010
        </kiadasiEv>
        <kiado>
            Akademia Kiado
        </kiado>
        <szerzok>
            <szerzo>
                Karen Holtzblatt
            </szerzo>
            <szerzo>
                Jessamny Burns Wendell
            </szerzo>
        </szerzok>
        <absztrakt>
            A felhasználó-központú tervezés technikájának gyakorlati kalauza.
        </absztrakt>
    </konyv>
    <konyv id="info_konyv_2">
        <cim>
            Formalis modszerek az informatikaban
        </cim>
        <kiadasiEv>
            2006
        </kiadasiEv>
        <kiado>
            Typotex Kiado
        </kiado>
        <szerzok>
            <szerzo>
                Pataricza Andras
            </szerzo>
        </szerzok>
    </konyv>
    <konyv id="info_konyv_3">
        <cim>
            Beginning Joomla
        </cim>
        <kiadasiEv>
            2009
        </kiadasiEv>
        <kiado>
            Oskola Antikvarium
        </kiado>
        <szerzok>
            <szerzo>
                Dan Rahmel
            </szerzo>
        </szerzok>
    </konyv>    
</konyvek>
