=== Petee99/E8HZ8D_XMLGyak/XMLTaskE8HZ8D/XMLSchemaE8HZ8D.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="beszallitasi_rendszer" type="beszallitasi_rendszerTipus">
        <xs:key name="key1">
            <xs:selector xpath="beszallito" />
            <xs:field xpath="@adoszam" />
        </xs:key>
        <xs:key name="key2">
            <xs:selector xpath="snowboard_felszereles" />
            <xs:field xpath="@azonosito" />
        </xs:key>
        <xs:key name="key3">
            <xs:selector xpath="viszontelado" />
            <xs:field xpath="@adoszam" />
        </xs:key>
        <xs:keyref name="keyref1" refer="key1">
            <xs:selector xpath="szallitja" />
            <xs:field xpath="@beszallito" />
        </xs:keyref>
        <xs:keyref name="keyref2" refer="key2">
            <xs:selector xpath="szallitja" />
            <xs:field xpath="@termek" />
        </xs:keyref>
        <xs:keyref name="keyref3" refer="key2">
            <xs:selector xpath="rendeles" />
            <xs:field xpath="@termek" />
        </xs:keyref>
        <xs:keyref name="keyref4" refer="key3">
            <xs:selector xpath="rendeles" />
            <xs:field xpath="@viszontelado" />
        </xs:keyref>
    </xs:element>

    <xs:complexType name="beszallitasi_rendszerTipus">
        <xs:sequence>
            <xs:element name="beszallito" type="beszallitoTipus" maxOccurs="unbounded" />
            <xs:element name="szallitja" type="szallitjaTipus" maxOccurs="unbounded" />
            <xs:element name="snowboard_felszereles" type="snowboard_felszerelesTipus" maxOccurs="unbounded" />
            <xs:element name="viszontelado" type="viszonteladoTipus" maxOccurs="unbounded" />
            <xs:element name="rendeles" type="rendelesTipus" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="beszallitoTipus">
        <xs:sequence>
            <xs:element name="cegnev" type="xs:string" />
            <xs:element name="cim" type="cimTipus" />
            <xs:element name="telefonszam" type="telefonszamTipus" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="adoszam" type="adoszamTipus" use="required" />
    </xs:complexType>

    <xs:complexType name="szallitjaTipus">
        <xs:sequence>
            <xs:element name="szallitasi_ido" type="xs:string" />
            <xs:element name="szallitasi_dij" type="xs:string" />
        </xs:sequence>
        <xs:attribute name="beszallito" type="adoszamTipus" use="required" />
        <xs:attribute name="termek" type="azonositoTipus" use="required" />
    </xs:complexType>

    <xs:complexType name="snowboard_felszerelesTipus">
        <xs:sequence>
            <xs:element name="tipus" type="xs:string" />
            <xs:element name="marka" type="xs:string" />
            <xs:element name="nev" type="xs:string" />
            <xs:element name="keszlet" type="xs:unsignedByte" />
            <xs:element minOccurs="0" name="szarmazasi_hely" type="xs:string" />
            <xs:element name="ar" type="xs:integer" />            
        </xs:sequence>
        <xs:attribute name="azonosito" type="azonositoTipus" use="required" />
    </xs:complexType>

    <xs:complexType name="viszonteladoTipus">
        <xs:sequence>
            <xs:element name="cegnev" type="xs:string" />
            <xs:element name="cim" type="cimTipus" />
            <xs:element name="telefonszam" type="telefonszamTipus" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="adoszam" type="adoszamTipus" use="required" />
    </xs:complexType>

    <xs:complexType name="rendelesTipus">
        <xs:sequence>
            <xs:element name="datum" type="xs:date" />
            <xs:element name="mennyiseg" type="xs:integer" />
        </xs:sequence>
        <xs:attribute name="rendeles_id" type="idTipus" use="required" />
        <xs:attribute name="viszontelado" type="adoszamTipus" use="required" />
        <xs:attribute name="termek" type="azonositoTipus" use="required" />
    </xs:complexType>

    <xs:simpleType name="adoszamTipus">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{8}[-]{1}[0-9]{1}[-]{1}[0-9]{2}" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="azonositoTipus">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{9}" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="idTipus">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-z]{3}[0-9]{3}" />
        </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="cimTipus">
        <xs:sequence>
            <xs:element name="zip" type="zipTipus" />
            <xs:element name="varos" type="xs:string" />
            <xs:element name="utca" type="xs:string" />
            <xs:element name="hazszam" type="hazszamTipus" />
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="zipTipus">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1000" />
            <xs:maxInclusive value="9999" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="hazszamTipus">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="telefonszamTipus">
        <xs:restriction base="xs:unsignedLong">
            <xs:pattern value="[0-9]{11}" />
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== Petee99/E8HZ8D_XMLGyak/XMLTaskE8HZ8D/XMLE8HZ8D_Modified.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><beszallitasi_rendszer xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./XMLSchemaE8HZ8D.xsd">
    
    <beszallito adoszam="11111111-2-33">
        <cegnev>SnowBoardStuff Bt.</cegnev>
        <cim>
            <zip>3535</zip>
            <varos>Miskolc</varos>
            <utca>Petofi ut</utca>
            <hazszam>13</hazszam>
        </cim>
        <telefonszam>06706027422</telefonszam>
        <telefonszam>06306027422</telefonszam>
    </beszallito>
    <beszallito adoszam="11111111-3-44">
        <cegnev>Kerekgyarto es Tarsa Zrt.</cegnev>
        <cim>
            <zip>2344</zip>
            <varos>Domsod</varos>
            <utca>Kossuth Lajos utca</utca>
            <hazszam>2</hazszam>
        </cim>
        <telefonszam>06206662710</telefonszam>
    </beszallito>
    <beszallito adoszam="11111111-3-35">
        <cegnev>We Sell SnwBrds Zrt.</cegnev>
        <cim>
            <zip>3341</zip>
            <varos>Szucs</varos>
            <utca>Kiraly utca</utca>
            <hazszam>54</hazszam>
        </cim>
        <telefonszam>06708899112</telefonszam>
    </beszallito>

    <szallitja beszallito="11111111-2-33" termek="111222333">
        <szallitasi_ido>3 nap</szallitasi_ido>
        <szallitasi_dij>3000 Ft</szallitasi_dij>
    </szallitja>
    <szallitja beszallito="11111111-2-33" termek="111222444">
        <szallitasi_ido>2 nap</szallitasi_ido>
        <szallitasi_dij>4000 Ft</szallitasi_dij>
    </szallitja>
    <szallitja beszallito="11111111-3-35" termek="111222555">
        <szallitasi_ido>5 nap</szallitasi_ido>
        <szallitasi_dij>1000 Ft</szallitasi_dij>
    </szallitja>

    <snowboard_felszereles azonosito="111222333">
        <tipus>Deszka</tipus>
        <marka>Nitro</marka>
        <nev>Team 159</nev>
        <keszlet>24</keszlet>
        <szarmazasi_hely>Ausztria</szarmazasi_hely>
        <ar>60000</ar>
    </snowboard_felszereles>
    <snowboard_felszereles azonosito="111222444">
        <tipus>Bakancs</tipus>
        <marka>Burton</marka>
        <nev>Moto BOA</nev>
        <keszlet>12</keszlet>
        <ar>50000</ar>
    </snowboard_felszereles>
    <snowboard_felszereles azonosito="111222555">
        <tipus>Kotes</tipus>
        <marka>Ride</marka>
        <nev>Rodeo</nev>
        <keszlet>8</keszlet>
        <szarmazasi_hely>USA</szarmazasi_hely>
        <ar>49000</ar>
    </snowboard_felszereles>

    <viszontelado adoszam="11111111-9-13">
        <cegnev>Snowboard Shop</cegnev>
        <cim>
            <zip>3508</zip>
            <varos>Miskolc</varos>
            <utca>Testvervarosok utja</utca>
            <hazszam>22</hazszam>
        </cim>
        <telefonszam>06706110100</telefonszam>
        <telefonszam>06206110100</telefonszam>
    </viszontelado>
    <viszontelado adoszam="11112222-2-33">
        <cegnev>Snowboards and CO.</cegnev>
        <cim>
            <zip>3521</zip>
            <varos>Miskolc</varos>
            <utca>Arpad ut</utca>
            <hazszam>56</hazszam>
        </cim>
        <telefonszam>06709856734</telefonszam>
    </viszontelado>
    <viszontelado adoszam="11113333-2-33">
        <cegnev>SnowboardStuff</cegnev>
        <cim>
            <zip>3522</zip>
            <varos>Miskolc</varos>
            <utca>Karolyi utca</utca>
            <hazszam>35</hazszam>
        </cim>
        <telefonszam>06208417632</telefonszam>
    </viszontelado>

    <rendeles rendeles_id="aaa111" termek="111222555" viszontelado="11111111-9-13">
        <datum>2021-09-15</datum>
        <mennyiseg>2</mennyiseg>
    </rendeles>
    <rendeles rendeles_id="aaa222" termek="111222444" viszontelado="11112222-2-33">
        <datum>2021-10-22</datum>
        <mennyiseg>2</mennyiseg>
    </rendeles>
    <rendeles rendeles_id="aaa333" termek="111222555" viszontelado="11113333-2-33">
        <datum>2021-11-09</datum>
        <mennyiseg>3</mennyiseg>
    </rendeles>

</beszallitasi_rendszer>
